### ISSUE TITLE
Update copyrights to 2020

### ISSUE THREAD

**Issue by rahlvers** [SNIA/Swordfish-Powershell-Toolkit#15]

**Comment by chris-lionetti** [comment]
How should it read? should is be 'Copyright 2019,2020' or replacement like 'Copyright 2020'?

**Comment by chris-lionetti** [comment]
Copyrights are updated in examples, In cases where they are not; its because I am pulling information from a REAL target and reporting back its value, which it tied to the vendor BMC Firmware.
