### ISSUE TITLE
Miscapitalization of Swordfish in cmdlet names and text

### ISSUE THREAD

**Issue by stmcginnis** [SNIA/Swordfish-Powershell-Toolkit#7]
Sev 1 priority 1 bug - official casing is Swordfish, not SwordFish. ;)

**Comment by chris-lionetti** [comment]
Well, powershell is case insensitive...but I see your point. I have renamed all commands, and all internal references for SwordFish have been changed to Swordfish. It all all proper, see latest build called 'Added Redfish

**Comment by chris-lionetti** [comment]
Fix is incorporated in most recent branch called 'Added Redfish'
